// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqbhpizgdfegcvuqjfgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYmhwaXpnZGZlZ2N2dXFqZmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTUxNzMsImV4cCI6MjA2MTk3MTE3M30.kuDqF1XS0zz3nbaNI9ZejjS_r7vsL4pQYOeE-fZS3SI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);